services:
  payment-api:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: payment-api
    image: payment-api
    volumes:
      - ./app:/app/app
    ports:
      - "8003:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - payment-db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/payment/health || exit 1" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  payment-db:
    image: postgres:17
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
      # - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  payment-db-data:
    name: payment-db-data
